RAISING_TO_ADMINISTRATOR = "Изменил права с Сотрудника на Администратора для пользователя %s"
LOWERING_FROM_ADMINISTRATOR = "Изменил права с Администратора на Сотрудника для пользователя %s"
REMOVE_EMPLOYEE = "Выгнал пользователя %s"
ADD_EMPLOYEE = "Пригласил пользователя %s"
CREATE_CAR = "Добавил "
REMOVE_CAR = "Удалил автомобиль"
ACCEPT_REQUEST = "Принял предлождение для "
REJECT_REQUEST = "Отклонил предлождение для "
