RAISING_TO_ADMINISTRATOR = "Назначил администратором пользователя %s"
LOWERING_FROM_ADMINISTRATOR = "Разжаловал пользователя %s"
REMOVE_EMPLOYEE = "Выгнал пользователя %s"
ADD_EMPLOYEE = "Пригласил пользователя %s"
CREATE_CAR = "Добавил "
REMOVE_CAR = "Удалил автомобиль"
